version: '3.7'

services:
  db:
    image: postgres:12.4-alpine
    env_file:
      - ../confs/db.env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
      - "./db/initdb_scripts:/docker-entrypoint-initdb.d"

  pre_matricula:
    image: 'ifrn/suap_ead_base:1.5.14'
    ports:
      - "7201:8000"
    env_file:
      - ../confs/db.env
      - ../confs/suap_ead.env
      - ../confs/pre_matricula.env
    volumes:
      - '../apps/pre_matricula:/apps/app'
      - '../libs/:/libs/'
      - "../volumes/media/pre_matricula:/media/sead/pre_matricula"
