version: '3.7'

services:
  db:
    image: postgres:12.4-alpine
    env_file:
      - ../confs/db.env
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
      - "./db/initdb_scripts:/docker-entrypoint-initdb.d"

  cmdb:
    image: 'ifrn/suap_ti:latest'
    ports:
      - "7201:8000"
    env_file:
      - ../confs/db.env
      - ../confs/cmdb.env
    volumes:
      - '../apps/cmdb:/apps/app'
      - "../volumes/media/cmdb:/media/sti/cmdb"
