#!/bin/bash
GREEN_COLOR='\033[1;32m'
ORANGE_COLOR='\033[0;33m'
RED_COLOR='\033[0;31m'
BLUE_COLOR='\033[1;34m'
NO_COLOR='\033[0m'

SERVICE_NAME=$(basename $(dirname $0))

pwd=$(pwd -P)

if [[ ! -f .env ]]; then
  cp example.env .env
fi

source "$pwd/.env"

echo_warning() {
  echo ${@:3} -e "$ORANGE_COLOR WARN: $(date +\"%F\ %T\") $1$NO_COLOR"
}

echo_danger() {
  echo ${@:3} -e "$RED_COLOR DANG: $(date +\"%F\ %T\") $1$NO_COLOR"
}

echo_info() {
  echo ${@:3} -e "$BLUE_COLOR INFO: $(date +\"%F\ %T\") $1$NO_COLOR"
}

echo_success() {
  echo ${@:3} -e "$GREEN_COLOR SUCC: $(date +\"%F\ %T\") $1$NO_COLOR"
}
