#!/bin/bash
source functions

echo_info "Reset confs"
rm -rf ../confs
mkdir ../confs
cp -r ../bin/confs_examples/* ../confs/

echo_info "Stop the world"
./down

echo_info "Reset volumes"
sudo rm -rf ../volumes

# echo_info "Prune system"
# docker system prune -a
